# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots["test_youtube_scrape_playlist playlist"] = {
    "_type": "playlist",
    "availability": None,
    "channel": "All Angles",
    "channel_follower_count": None,
    "channel_id": "UCgBRykS2v-WV2YYUpR2V9jw",
    "channel_url": "https://www.youtube.com/channel/UCgBRykS2v-WV2YYUpR2V9jw",
    "description": "This is an overview of linear algebra, from vectors and dot products all the way to eigenvalues and the singular value decomposition.  We focus on applications such as Fourier analysis, artificial intelligence, dynamic systems and more.",
    "entries": [
        {
            "__x_forwarded_for_ip": None,
            "_type": "url",
            "availability": None,
            "channel": "All Angles",
            "channel_id": "UCgBRykS2v-WV2YYUpR2V9jw",
            "channel_is_verified": None,
            "channel_url": "https://www.youtube.com/channel/UCgBRykS2v-WV2YYUpR2V9jw",
            "description": None,
            "duration": 2117,
            "id": "KbyYTjfgZJI",
            "ie_key": "Youtube",
            "live_status": None,
            "release_timestamp": None,
            "thumbnails": [
                {
                    "height": 94,
                    "url": "https://i.ytimg.com/vi/KbyYTjfgZJI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAENOcLncGyzkfcW5M27w5FjqgFsg",
                    "width": 168,
                },
                {
                    "height": 110,
                    "url": "https://i.ytimg.com/vi/KbyYTjfgZJI/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCriKpyL4BDsujAiucE_7jdJljwvA",
                    "width": 196,
                },
                {
                    "height": 138,
                    "url": "https://i.ytimg.com/vi/KbyYTjfgZJI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDOwJeOXQhH-o87g5kzA9kuU4FIFw",
                    "width": 246,
                },
                {
                    "height": 188,
                    "url": "https://i.ytimg.com/vi/KbyYTjfgZJI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAHwUCWM5y9Tn83z9MsLNDjBgldUw",
                    "width": 336,
                },
            ],
            "timestamp": 1701648000,
            "title": "Vector spaces | Linear algebra episode 1",
            "uploader": "All Angles",
            "uploader_id": "@AllAnglesMath",
            "uploader_url": "https://www.youtube.com/@AllAnglesMath",
            "url": "https://www.youtube.com/watch?v=KbyYTjfgZJI",
            "view_count": 4700,
        },
        {
            "__x_forwarded_for_ip": None,
            "_type": "url",
            "availability": None,
            "channel": "All Angles",
            "channel_id": "UCgBRykS2v-WV2YYUpR2V9jw",
            "channel_is_verified": None,
            "channel_url": "https://www.youtube.com/channel/UCgBRykS2v-WV2YYUpR2V9jw",
            "description": None,
            "duration": 2002,
            "id": "mCi_0ML0lG8",
            "ie_key": "Youtube",
            "live_status": None,
            "release_timestamp": None,
            "thumbnails": [
                {
                    "height": 94,
                    "url": "https://i.ytimg.com/vi/mCi_0ML0lG8/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB4ImYLfZCMwnZRuw9NrPKff6EyhA",
                    "width": 168,
                },
                {
                    "height": 110,
                    "url": "https://i.ytimg.com/vi/mCi_0ML0lG8/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCcWkfF4di4hi8GFJtlrCXuxnXkJQ",
                    "width": 196,
                },
                {
                    "height": 138,
                    "url": "https://i.ytimg.com/vi/mCi_0ML0lG8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD259XiOdeLZ6_JXW_pM-0ODJcgjw",
                    "width": 246,
                },
                {
                    "height": 188,
                    "url": "https://i.ytimg.com/vi/mCi_0ML0lG8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDuupnkIIP507QhYSK12Dn5Rf9K7A",
                    "width": 336,
                },
            ],
            "timestamp": 1701648000,
            "title": "Lengths, angles, projection, correlation | Linear algebra episode 2",
            "uploader": "All Angles",
            "uploader_id": "@AllAnglesMath",
            "uploader_url": "https://www.youtube.com/@AllAnglesMath",
            "url": "https://www.youtube.com/watch?v=mCi_0ML0lG8",
            "view_count": 3300,
        },
        {
            "__x_forwarded_for_ip": None,
            "_type": "url",
            "availability": None,
            "channel": "All Angles",
            "channel_id": "UCgBRykS2v-WV2YYUpR2V9jw",
            "channel_is_verified": None,
            "channel_url": "https://www.youtube.com/channel/UCgBRykS2v-WV2YYUpR2V9jw",
            "description": None,
            "duration": 2308,
            "id": "dn0SSkgCiII",
            "ie_key": "Youtube",
            "live_status": None,
            "release_timestamp": None,
            "thumbnails": [
                {
                    "height": 94,
                    "url": "https://i.ytimg.com/vi/dn0SSkgCiII/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAr7Ejy7YIChN4gj9TTUXCHcnv5-A",
                    "width": 168,
                },
                {
                    "height": 110,
                    "url": "https://i.ytimg.com/vi/dn0SSkgCiII/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCql7ocVPdfZR6D8r3Z1lF9zhVzdA",
                    "width": 196,
                },
                {
                    "height": 138,
                    "url": "https://i.ytimg.com/vi/dn0SSkgCiII/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAAd_irTz7kgwynJGh5zyV45Jg54g",
                    "width": 246,
                },
                {
                    "height": 188,
                    "url": "https://i.ytimg.com/vi/dn0SSkgCiII/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDRPYSrJwgyxFYEecZQ-YyXotOOrg",
                    "width": 336,
                },
            ],
            "timestamp": 1704326400,
            "title": "The math behind music | Linear algebra episode 3",
            "uploader": "All Angles",
            "uploader_id": "@AllAnglesMath",
            "uploader_url": "https://www.youtube.com/@AllAnglesMath",
            "url": "https://www.youtube.com/watch?v=dn0SSkgCiII",
            "view_count": 2700,
        },
        {
            "__x_forwarded_for_ip": None,
            "_type": "url",
            "availability": None,
            "channel": "All Angles",
            "channel_id": "UCgBRykS2v-WV2YYUpR2V9jw",
            "channel_is_verified": None,
            "channel_url": "https://www.youtube.com/channel/UCgBRykS2v-WV2YYUpR2V9jw",
            "description": None,
            "duration": 1664,
            "id": "hsJ1-6ybvGM",
            "ie_key": "Youtube",
            "live_status": None,
            "release_timestamp": None,
            "thumbnails": [
                {
                    "height": 94,
                    "url": "https://i.ytimg.com/vi/hsJ1-6ybvGM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBjIsUibet6btUD1L--yzcCicONVw",
                    "width": 168,
                },
                {
                    "height": 110,
                    "url": "https://i.ytimg.com/vi/hsJ1-6ybvGM/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBuh_7lxPAcpjFjvpEh6dApyzUlWA",
                    "width": 196,
                },
                {
                    "height": 138,
                    "url": "https://i.ytimg.com/vi/hsJ1-6ybvGM/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDHA-Q_Zcb0oahyQygDVR2i366hQg",
                    "width": 246,
                },
                {
                    "height": 188,
                    "url": "https://i.ytimg.com/vi/hsJ1-6ybvGM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAvHL94HTEYed-umiba8n3VyZPFlQ",
                    "width": 336,
                },
            ],
            "timestamp": 1707004800,
            "title": "Linear transformations | Linear algebra episode 4",
            "uploader": "All Angles",
            "uploader_id": "@AllAnglesMath",
            "uploader_url": "https://www.youtube.com/@AllAnglesMath",
            "url": "https://www.youtube.com/watch?v=hsJ1-6ybvGM",
            "view_count": 1700,
        },
        {
            "__x_forwarded_for_ip": None,
            "_type": "url",
            "availability": None,
            "channel": "All Angles",
            "channel_id": "UCgBRykS2v-WV2YYUpR2V9jw",
            "channel_is_verified": None,
            "channel_url": "https://www.youtube.com/channel/UCgBRykS2v-WV2YYUpR2V9jw",
            "description": None,
            "duration": 1164,
            "id": "JAyVH1urA3w",
            "ie_key": "Youtube",
            "live_status": None,
            "release_timestamp": None,
            "thumbnails": [
                {
                    "height": 94,
                    "url": "https://i.ytimg.com/vi/JAyVH1urA3w/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAZ4d6-oDW0XOk8lVf7iXf2G1bLRg",
                    "width": 168,
                },
                {
                    "height": 110,
                    "url": "https://i.ytimg.com/vi/JAyVH1urA3w/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB2suys06HNMn3ATcJK21VWFghq4A",
                    "width": 196,
                },
                {
                    "height": 138,
                    "url": "https://i.ytimg.com/vi/JAyVH1urA3w/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCMrnsJa7wSHltH81LGNazo8C0QbA",
                    "width": 246,
                },
                {
                    "height": 188,
                    "url": "https://i.ytimg.com/vi/JAyVH1urA3w/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDf32yZKC-ksS1px2eGtep3-n8tww",
                    "width": 336,
                },
            ],
            "timestamp": 1707004800,
            "title": "Interesting matrix examples | Linear algebra episode 5",
            "uploader": "All Angles",
            "uploader_id": "@AllAnglesMath",
            "uploader_url": "https://www.youtube.com/@AllAnglesMath",
            "url": "https://www.youtube.com/watch?v=JAyVH1urA3w",
            "view_count": 1600,
        },
        {
            "__x_forwarded_for_ip": None,
            "_type": "url",
            "availability": None,
            "channel": "All Angles",
            "channel_id": "UCgBRykS2v-WV2YYUpR2V9jw",
            "channel_is_verified": None,
            "channel_url": "https://www.youtube.com/channel/UCgBRykS2v-WV2YYUpR2V9jw",
            "description": None,
            "duration": 2076,
            "id": "nNNPY-NgIJk",
            "ie_key": "Youtube",
            "live_status": None,
            "release_timestamp": None,
            "thumbnails": [
                {
                    "height": 94,
                    "url": "https://i.ytimg.com/vi/nNNPY-NgIJk/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDXKuJNc1-Fsvf1cjAf9E7jTiKV8A",
                    "width": 168,
                },
                {
                    "height": 110,
                    "url": "https://i.ytimg.com/vi/nNNPY-NgIJk/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLD8wo2URYYMmWG7HJoRyentDqtF6g",
                    "width": 196,
                },
                {
                    "height": 138,
                    "url": "https://i.ytimg.com/vi/nNNPY-NgIJk/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDVCymfkk8Qxn34aLThIdc6j1gMFA",
                    "width": 246,
                },
                {
                    "height": 188,
                    "url": "https://i.ytimg.com/vi/nNNPY-NgIJk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAGVgEzi_qQ8hugLD8g4Ne7cM0yQA",
                    "width": 336,
                },
            ],
            "timestamp": 1709510400,
            "title": "Groups of matrices | Linear algebra episode 6",
            "uploader": "All Angles",
            "uploader_id": "@AllAnglesMath",
            "uploader_url": "https://www.youtube.com/@AllAnglesMath",
            "url": "https://www.youtube.com/watch?v=nNNPY-NgIJk",
            "view_count": 2100,
        },
        {
            "__x_forwarded_for_ip": None,
            "_type": "url",
            "availability": None,
            "channel": "All Angles",
            "channel_id": "UCgBRykS2v-WV2YYUpR2V9jw",
            "channel_is_verified": None,
            "channel_url": "https://www.youtube.com/channel/UCgBRykS2v-WV2YYUpR2V9jw",
            "description": None,
            "duration": 1047,
            "id": "gAPlRlmhXyI",
            "ie_key": "Youtube",
            "live_status": None,
            "release_timestamp": None,
            "thumbnails": [
                {
                    "height": 94,
                    "url": "https://i.ytimg.com/vi/gAPlRlmhXyI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDApNWBSsCffdXjx_EHYky0dl0fRw",
                    "width": 168,
                },
                {
                    "height": 110,
                    "url": "https://i.ytimg.com/vi/gAPlRlmhXyI/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDkoSJvzfBa9cT9uC0YR3kL5MMe-A",
                    "width": 196,
                },
                {
                    "height": 138,
                    "url": "https://i.ytimg.com/vi/gAPlRlmhXyI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDjuES-bZcMb0qleKNOf_DHVIMXlg",
                    "width": 246,
                },
                {
                    "height": 188,
                    "url": "https://i.ytimg.com/vi/gAPlRlmhXyI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB_Ua0QtiZzd7XglyY5cseaAWz_Fw",
                    "width": 336,
                },
            ],
            "timestamp": 1714780800,
            "title": "A change of perspective | Linear algebra episode 7",
            "uploader": "All Angles",
            "uploader_id": "@AllAnglesMath",
            "uploader_url": "https://www.youtube.com/@AllAnglesMath",
            "url": "https://www.youtube.com/watch?v=gAPlRlmhXyI",
            "view_count": 1600,
        },
        {
            "__x_forwarded_for_ip": None,
            "_type": "url",
            "availability": None,
            "channel": "All Angles",
            "channel_id": "UCgBRykS2v-WV2YYUpR2V9jw",
            "channel_is_verified": None,
            "channel_url": "https://www.youtube.com/channel/UCgBRykS2v-WV2YYUpR2V9jw",
            "description": None,
            "duration": 2117,
            "id": "M35iuFAxQxY",
            "ie_key": "Youtube",
            "live_status": None,
            "release_timestamp": None,
            "thumbnails": [
                {
                    "height": 94,
                    "url": "https://i.ytimg.com/vi/M35iuFAxQxY/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDRB38SRNDvb-jW_t0Gt1vfD-9VrA",
                    "width": 168,
                },
                {
                    "height": 110,
                    "url": "https://i.ytimg.com/vi/M35iuFAxQxY/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBumFHESyHxyVja-NSCilX3zqXQ5A",
                    "width": 196,
                },
                {
                    "height": 138,
                    "url": "https://i.ytimg.com/vi/M35iuFAxQxY/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBoxGCShkIPuJf2vrASyG0IqICtZA",
                    "width": 246,
                },
                {
                    "height": 188,
                    "url": "https://i.ytimg.com/vi/M35iuFAxQxY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDs8cZ67orOSZIhxqXWoD7yWCOUVQ",
                    "width": 336,
                },
            ],
            "timestamp": 1714780800,
            "title": "Eigenvalues and eigenvectors | Linear algebra episode 8",
            "uploader": "All Angles",
            "uploader_id": "@AllAnglesMath",
            "uploader_url": "https://www.youtube.com/@AllAnglesMath",
            "url": "https://www.youtube.com/watch?v=M35iuFAxQxY",
            "view_count": 3300,
        },
        {
            "__x_forwarded_for_ip": None,
            "_type": "url",
            "availability": None,
            "channel": "All Angles",
            "channel_id": "UCgBRykS2v-WV2YYUpR2V9jw",
            "channel_is_verified": None,
            "channel_url": "https://www.youtube.com/channel/UCgBRykS2v-WV2YYUpR2V9jw",
            "description": None,
            "duration": 1877,
            "id": "iNEK9IEWKQI",
            "ie_key": "Youtube",
            "live_status": None,
            "release_timestamp": None,
            "thumbnails": [
                {
                    "height": 94,
                    "url": "https://i.ytimg.com/vi/iNEK9IEWKQI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDLgXxs6eGnh89CvVKY0I71u-gnmQ",
                    "width": 168,
                },
                {
                    "height": 110,
                    "url": "https://i.ytimg.com/vi/iNEK9IEWKQI/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB0O9GkOEpIXsuGtLqRHdHNmDJP6Q",
                    "width": 196,
                },
                {
                    "height": 138,
                    "url": "https://i.ytimg.com/vi/iNEK9IEWKQI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLALwJiJiB3kT775qwI1Cp2ZB44nFw",
                    "width": 246,
                },
                {
                    "height": 188,
                    "url": "https://i.ytimg.com/vi/iNEK9IEWKQI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAirWNOUCYUQvhCDTgMYcduyRSLFg",
                    "width": 336,
                },
            ],
            "timestamp": 1720051200,
            "title": "Singular Value Decomposition | Linear algebra episode 9",
            "uploader": "All Angles",
            "uploader_id": "@AllAnglesMath",
            "uploader_url": "https://www.youtube.com/@AllAnglesMath",
            "url": "https://www.youtube.com/watch?v=iNEK9IEWKQI",
            "view_count": 3300,
        },
    ],
    "epoch": "<ignored>",
    "extractor": "youtube:tab",
    "extractor_key": "YoutubeTab",
    "id": "PLffJUy1BnWj13MxDDbXWcbPzna0UESH59",
    "modified_date": "20240606",
    "original_url": "https://www.youtube.com/playlist?list=PLffJUy1BnWj13MxDDbXWcbPzna0UESH59",
    "playlist_count": 9,
    "release_year": None,
    "tags": [],
    "thumbnails": "<ignored>",
    "title": "Linear algebra",
    "uploader": "All Angles",
    "uploader_id": "@AllAnglesMath",
    "uploader_url": "https://www.youtube.com/@AllAnglesMath",
    "view_count": 3640,
    "webpage_url": "https://www.youtube.com/playlist?list=PLffJUy1BnWj13MxDDbXWcbPzna0UESH59",
    "webpage_url_basename": "playlist",
    "webpage_url_domain": "youtube.com",
}
